name: kiss-lint
author: jedahan
description: run kiss-lint on your kiss repositories
branding:
  icon: 'moon'  
  color: 'blue'
inputs:
  kisspath:
    description: :-delimited list of paths to check, relative to the repository root
    required: true
    default: '.'
runs:
  using: 'composite'
  steps:
    - run: |
        cd $GITHUB_WORKSPACE
        export KISS_PATH=$(echo ${{ inputs.kisspath }})
        output=$(curl --silent --location \
          https://raw.githubusercontent.com/jedahan/kiss-repo/60400666fdfe6e1f939e752eaa92039d43ada848/kiss-lint/files/kiss-lint \
          | bash |& sed -r 's#^(warning|error) ([a-z./]+) (.*)#::\1 file=\{\2\}::\2: \3#'; true)
        echo "$output" | tee /dev/stdout | grep --quiet --invert-match "^error"
      shell: bash
