name: kiss-lint
author: jedahan
description: run kiss-lint on your kiss repositories
branding:
  icon: 'moon'  
  color: 'blue'
inputs:
  kisspath:
    description: :-delimited list of paths to check, relative to the repository root
    required: true
    default: '.'
runs:
  using: 'composite'
  steps:
    - run: |
        export KISS_PATH=$(echo ${{ inputs.kisspath }} | /usr/bin/sed -e "s|^|${GITHUB_WORKSPACE}/|" -e "s|:|:${GITHUB_WORKSPACE}/|")
        output=$(/usr/bin/curl --silent --location \
          https://raw.githubusercontent.com/jedahan/kiss-repo/1370e9d22452e0646fcfa777c54747848038a0c5/kiss-lint/files/kiss-lint \
         | /usr/bin/bash 2>&1 | sed -e 's|^.*error: \([a-zA-Z/\.]\)+: |::info file={\1}::|' -e 's|^.*warning: |::warning ::|')
        echo $output
        test -z "$output"
      shell: bash
